[package]
name = "polyserve"
version = "0.1.0"
authors = ["Richard Carls <richard.j.carls@gmail.com>"]
edition = "2018"

[[bin]]
name = "polyserve"
path = "src/bin/main.rs"

[lib]
name = "polyserve"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
cascade = "1.0.0"