[package]
name = "polyserve"
version = "0.1.0"
authors = ["Richard Carls <richard.j.carls@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[[bin]]
name = "polyserve"
path = "src/bin/main.rs"

[lib]
name = "polyserve"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
async-std = "1.9"
async-trait = "0.1.50"
async-native-tls = "0.3.3"
serde = { version = "1.0.128", features = ["derive"] }
serde_json = "1.0.66"
mime = "0.3.16"
mime_guess = "2.0.3"
chrono = "0.4.19"
handlebars = "4.1.1"
cascade = "1.0.0"
clap = { git = "https://github.com/clap-rs/clap/" }